version: "3.8"

services:
  envoy:
    image: envoyproxy/envoy:v1.18.2
    container_name: envoy
    volumes:
      - type: bind
        source: ./envoy.yaml
        target: /etc/envoy/envoy.yaml
    ports:
      - "8081:8081"
      - "8082:8082"
    command:
      - "envoy"
      - "-c"
      - "/etc/envoy/envoy.yaml"
    extra_hosts:
    - "host.docker.internal:host-gateway"
  backend:
    image: simmonmt/xmaslist/backend
    container_name: backend
    volumes:
      - type: volume
        source: xmaslist_database
        target: /db
    secrets:
      - backend_session_secret
    command:
      - "--port=9090"
      - "--db=/db/db.sqlite"
      - "--session_secret=/run/secrets/backend_session_secret"
    ports:
      - "9090:9090"
  frontend:
    image: simmonmt/xmaslist/frontend
    container_name: frontend
    ports:
      - "8080:8080"

volumes:
  xmaslist_database:
    external: true

secrets:
  backend_session_secret:
    file: ./session_secret.txt
