#!/bin/bash

set -e

function die {
    echo "${PROGNAME}:" "$@" >&2
    exit 1
}

function usage {
    echo "Usage: ${PROGNAME} --db=db_file compose_args..." >&2
    exit 2
}

GETOPT=getopt
if which brew >/dev/null 2>&1 ; then
    prefix=$(brew --prefix gnu-getopt 2>/dev/null)
    if [[ -n "${prefix}" ]] ; then
	GETOPT="${prefix}/bin/getopt"
    fi
fi

PROGNAME=$(basename "$0")
PROGDIR=$(dirname "$0")

options=$(${GETOPT} -o '' --longoptions db: -- "$@")
[[ $? -ne 0 ]] && usage
eval set -- "$options"
while : ; do
    case "$1" in
        --db)
            export XMASLIST_DATABASE="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            break
            ;;
    esac
    shift
done

docker-compose \
  --project-directory ${PROGDIR} \
  --project-name xmaslist
  -f ${PROGDIR}/base.yml \
  -f ${PROGDIR}/dev.yml \
  "$@"
