#!/bin/bash

set -e

function die {
    echo "${PROGNAME}:" "$@" >&2
    exit 1
}

function usage {
    echo "Usage: ${PROGNAME} [--rm]" >&2
    exit 2
}

PROGNAME=$(basename "$0")

VOL=xmaslist_session_secret

tmpfile=$(mktemp)
trap "rm -f ${tmpfile}" EXIT INT QUIT TERM

docker volume create ${VOL}

dd status=none if=/dev/urandom count=8192 >${tmpfile}
[[ -z "${tmpfile}" ]] && die "no random bits"

sha256sum <${tmpfile} |cut -d" " -f1 | \
    docker run --rm -i --name ${VOL}_create \
           -v ${VOL}:/vol alpine tee /vol/session_secret.txt

docker run --rm --name ${VOL}_verify -v ${VOL}:/vol alpine \
       cat /vol/session_secret.txt
