version: "3.8"

services:
  envoy:
    ports:
      - target: 8080
        published: 3400
        protocol: tcp
        mode: host

  backend:
    volumes:
      - type: volume
        source: xmaslist_database
        target: /db
      - type: volume
        read_only: true
        source: xmaslist_session_secret
        target: /secret

volumes:
  xmaslist_database:
    external: true
  xmaslist_session_secret:
    external: true
