version: "3.8"

services:
  backend:
    volumes:
      - type: volume
        source: xmaslist_database
        target: /db
      - type: volume
        read_only: true
        source: xmaslist_session_secret
        target: /secret

volumes:
  xmaslist_database:
    external: true
  xmaslist_session_secret:
    external: true
