#!/bin/bash

set -e

function die {
    echo "${PROGNAME}:" "$@" >&2
    exit 1
}

function usage {
    echo "Usage: ${PROGNAME} [--rm]" >&2
    exit 2
}

function user_add {
    local dbfile="$1"
    local username="$2"
    local fullname="$3"
    local password="$4"

    [[ -n "${dbfile}" ]] || die "missing dbfile"
    [[ -n "${username}" ]] || die "missing username"
    [[ -n "${fullname}" ]] || die "missing fullname"
    [[ -n "${password}" ]] || die "missing password"

    local adminflag=""
    if [[ "$5" == "admin" ]]; then
        adminflag="--admin"
    elif [[ -n "$5" ]] ; then
        die "bad admin value"
    fi

    bazel-bin/backend/cmd/db_util/db_util_/db_util user add ${adminflag} \
          "${dbfile}" "${username}" "${fullname}" "${password}"
}

PROGNAME=$(basename "$0")

options=$(getopt -o '' --longoptions rm,load_test_data -- "$@")
[[ $? -ne 0 ]] && usage
eval set -- "$options"
while : ; do
    case "$1" in
        --rm)
            RMVOL=1
            ;;
        --load_test_data)
            LOADTESTDATA=1
            ;;
        --)
            shift
            break
            ;;
    esac
    shift
done

VOL=xmaslist_database

if docker volume inspect ${VOL} >/dev/null 2>&1 ; then
    [[ "$RMVOL" -ne 1 ]] && die "${VOL} exists"
    echo "Removing existing volume ${VOL}"
    docker volume rm ${VOL}
fi

DB_TMPFILE=/tmp/db.sqlite
[[ -f "${DB_TMPFILE}" ]] && rm "${DB_TMPFILE}"

sqlite3 ${DB_TMPFILE} <db/schema.txt
if [[ "${LOADTESTDATA}" -eq 1 ]] ; then
    bazel build backend/cmd/db_util

    user_add ${DB_TMPFILE} a "User A" aa admin
    user_add ${DB_TMPFILE} b "User B" bb
fi

docker volume create ${VOL}
docker container create \
       --name xmaslist_database_create \
       -v ${VOL}:/db \
       alpine
docker cp /tmp/db.sqlite xmaslist_database_create:/db

docker container rm xmaslist_database_create
